### ISSUE TITLE
Server doesn't work

### ISSUE THREAD

**Issue by LucioARavelli** [BSRevival/BlackRevivalCore#3]
I have a problem. I followed the steps given in the README archive, but for some reason this happens:
![image](https://github.com/BSRevival/BlackRevivalCore/assets/120160308/ca7b4c72-c3af-4b55-a78b-ab143ac0417a)
The only problem I had with the steps is that the Visual Studio doesn't say "BlackRevivalServer", but instead say the names of the folders BlackRevival.APIServer, BlackRevival.GameServer and BlackRevival.InstanceManager.
What I'm doing wrong?
Thank you

**Comment by BSRevival** [comment]
I will be updating the readme here shortly, We have moved to Rider as the IDE of choice for development on this and are now starting to implement database tables so it will require a mariadb install or xampp.

**Comment by LucioARavelli** [comment]
Thank you very much! I will be waiting for the update 😊❤️
